"""Add room_id to Task model for dashboard

Revision ID: 7659c6796a6b
Revises: 47ded9400db4
Create Date: 2025-10-08 12:35:17.917436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7659c6796a6b'
down_revision = '47ded9400db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'room_id')
    # ### end Alembic commands ###