"""Implementace pokročilých rezervací a dynamické cenotvorby

Revision ID: d918d4e197ba
Revises: 4cfeee06942b
Create Date: 2025-10-08 13:00:54.903244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd918d4e197ba'
down_revision = '4cfeee06942b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rate_plans_id'), 'rate_plans', ['id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_table('restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_stay', sa.Integer(), nullable=True),
    sa.Column('closed_to_arrival', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('rate_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restrictions_id'), 'restrictions', ['id'], unique=False)
    op.create_table('room_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_blocks_id'), 'room_blocks', ['id'], unique=False)
    op.add_column('guests', sa.Column('preferences', sa.String(length=1000), nullable=True))
    op.add_column('guests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('reservations', sa.Column('accommodation_price', sa.Float(), nullable=False))
    op.add_column('reservations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reservations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('reservations', 'total_price')
    op.add_column('room_charges', sa.Column('description', sa.String(length=255), nullable=False))
    op.alter_column('room_charges', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('rooms', 'price_per_night')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price_per_night', mysql.FLOAT(), nullable=True))
    op.alter_column('room_charges', 'item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('room_charges', 'description')
    op.add_column('reservations', sa.Column('total_price', mysql.FLOAT(), nullable=True))
    op.drop_column('reservations', 'updated_at')
    op.drop_column('reservations', 'created_at')
    op.drop_column('reservations', 'accommodation_price')
    op.drop_column('payments', 'notes')
    op.drop_column('guests', 'created_at')
    op.drop_column('guests', 'preferences')
    op.drop_index(op.f('ix_room_blocks_id'), table_name='room_blocks')
    op.drop_table('room_blocks')
    op.drop_index(op.f('ix_restrictions_id'), table_name='restrictions')
    op.drop_table('restrictions')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_rate_plans_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    # ### end Alembic commands ###